---
server:  port: 8888
  
spring:  profiles:    active: native
  cloud:    config:      server:        native:          search-locations: C:\Users\blizz\dev\repository\alura-microservices-spring-cloud