---
server:  port: 8888
  
spring:
  cloud:    config:      server:        git:          uri: https://github.com/WildBaconDev/Alura-config-server          search-paths: fornecedor, loja, transportador